import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	keywords: ["Next.js", "TypeScript", "Geist UI", "Web Development"],
	authors: { name: "Next.js Team", url: "https://nextjs.org" },
};

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="sk">
			<body>{children}</body>
		</html>
	);
}
